# Import Libraries
Any libraries we import for data handling will go here.

In [18]:
import pandas as pd

# Load the Dataset
We used pandas to read the CSV file into a DataFrame.

In [19]:
chicago = pd.read_csv('Chicago_Crime_Dataset_2020.csv')
LA = pd.read_csv('LA_Crime_Dataset_2020_to_2024.csv')
print("Dataset loaded successfully.")

Dataset loaded successfully.

# Chicago Information
We printed basic information about the DataFrame, such as its shape, columns, and a preview of the first few rows.

In [21]:
print(f"Dataset shape: {chicago.shape}")
print(f"Columns: {list(chicago.columns)}")

Dataset shape: (212702, 22)
Columns: ['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type', 'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat', 'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate', 'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude', 'Location']

In [22]:
chicago.head(5)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,12262588,JE104819,12/31/2020 11:59:00 PM,017XX N CICERO AVE,0810,THEFT,OVER $500,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,37.0,25.0,06,1144138.0,1910955.0,2020,2021 Jan 08 03:39:34 PM,41.911684,-87.745918,POINT (-87.745917518 41.9116839)
1,12258658,JE100080,12/31/2020 11:51:00 PM,013XX S HOMAN AVE,0430,BATTERY,AGGRAVATED - OTHER DANGEROUS WEAPON,STREET,False,False,...,24.0,29.0,04B,1153918.0,1893431.0,2020,2021 Jan 07 03:41:47 PM,41.863407,-87.710456,POINT (-87.710455868 41.863406877)
2,12274737,JE118886,12/31/2020 11:45:00 PM,001XX E WACKER DR,0810,THEFT,OVER $500,HOTEL / MOTEL,False,False,...,42.0,32.0,06,1177683.0,1902638.0,2020,2021 Jan 23 03:39:36 PM,41.888165,-87.622937,POINT (-87.622937212 41.888165132)
3,12258623,JD475015,12/31/2020 11:45:00 PM,056XX S WABASH AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,20.0,40.0,08B,1177678.0,1867609.0,2020,2021 Jan 07 03:41:47 PM,41.792043,-87.624018,POINT (-87.624017919 41.792043078)
4,12263896,JE105660,12/31/2020 11:45:00 PM,049XX S FORRESTVILLE AVE,0810,THEFT,OVER $500,RESIDENCE,False,False,...,4.0,38.0,06,1180760.0,1872402.0,2020,2021 Jan 10 03:39:57 PM,41.805125,-87.612569,POINT (-87.612569477 41.805125154)

# LA Information
We printed basic information about the DataFrame, such as its shape, columns, and a preview of the first few rows.

In [23]:
print(f"Dataset shape: {LA.shape}")
print(f"Columns: {list(LA.columns)}")

Dataset shape: (1004894, 28)
Columns: ['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME', 'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes', 'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc', 'Weapon Used Cd', 'Weapon Desc', 'Status', 'Status Desc', 'Crm Cd 1', 'Crm Cd 2', 'Crm Cd 3', 'Crm Cd 4', 'LOCATION', 'Cross Street', 'LAT', 'LON']

In [24]:
LA.head(5)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,211507896,2021 Apr 11 12:00:00 AM,2020 Nov 07 12:00:00 AM,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,7800 BEEMAN AV,NaN,34.2124,-118.4092
1,201516622,2020 Oct 21 12:00:00 AM,2020 Oct 18 12:00:00 AM,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,ATOLL AV,N GAULT,34.1993,-118.4203
2,240913563,2024 Dec 10 12:00:00 AM,2020 Oct 30 12:00:00 AM,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,14600 SYLVAN ST,NaN,34.1847,-118.4509
3,210704711,2020 Dec 24 12:00:00 AM,2020 Dec 24 12:00:00 AM,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,6000 COMEY AV,NaN,34.0339,-118.3747
4,201418201,2020 Oct 03 12:00:00 AM,2020 Sep 29 12:00:00 AM,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,4700 LA VILLA MARINA,NaN,33.9813,-118.4350

# Cleaning

The Chicago dataset "Date" refers to the date and time that the event occured. Therefore we will also use the date and time the event occurd (DATE OCC) from the LA Dataset. Using datetime we formated the DATE OCC to match that of Chicago and droped all row that were not from the year 2020.

In [31]:
LA['DATE OCC'] = pd.to_datetime(LA['DATE OCC'])

LA = LA[LA['DATE OCC'].dt.year == 2020]

# Reformat to match the Chicago format: %m/%d/%Y %I:%M:%S %p
LA['DATE OCC'] = LA['DATE OCC'].dt.strftime('%m/%d/%Y %I:%M:%S %p')

LA.head(5)

/var/folders/3f/pww76vqd6_b67qs48cp32q980000gn/T/ipykernel_3857/2187665707.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  LA['DATE OCC'] = pd.to_datetime(LA['DATE OCC'])

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,211507896,2021 Apr 11 12:00:00 AM,11/07/2020 12:00:00 AM,845,15,N Hollywood,1502,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,7800 BEEMAN AV,NaN,34.2124,-118.4092
1,201516622,2020 Oct 21 12:00:00 AM,10/18/2020 12:00:00 AM,1845,15,N Hollywood,1521,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230.0,NaN,NaN,NaN,ATOLL AV,N GAULT,34.1993,-118.4203
2,240913563,2024 Dec 10 12:00:00 AM,10/30/2020 12:00:00 AM,1240,9,Van Nuys,933,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,14600 SYLVAN ST,NaN,34.1847,-118.4509
3,210704711,2020 Dec 24 12:00:00 AM,12/24/2020 12:00:00 AM,1310,7,Wilshire,782,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331.0,NaN,NaN,NaN,6000 COMEY AV,NaN,34.0339,-118.3747
4,201418201,2020 Oct 03 12:00:00 AM,09/29/2020 12:00:00 AM,1830,14,Pacific,1454,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,4700 LA VILLA MARINA,NaN,33.9813,-118.4350

In [32]:
LA.shape

(199847, 28)

In [30]:
chicago.shape

(212702, 22)

# Save Cleaned DataFrames Back to CSV
After cleaning the dataframes, we save them as cleaned CSV files to upload to GitHub since they will be much smaller after cleaning.

In [ ]:
# Save Cleaned DataFrames to New CSV Files
# This saves the cleaned data as new files without overwriting the originals.

# Save Chicago dataframe to a new file
chicago.to_csv('Chicago_Crime_Cleaned.csv', index=False)
print("Chicago cleaned CSV saved as 'Chicago_Crime_Cleaned.csv'.")

# Save LA dataframe to a new file
LA.to_csv('LA_Crime_Cleaned.csv', index=False)
print("LA cleaned CSV saved as 'LA_Crime_Cleaned.csv'.")